### ISSUE TITLE
Upgrade deprecated node.js from 12 to 16 broke docker-login/v1

### ISSUE THREAD

**Issue by magdalena-ksiazek** [Azure/docker-login#49] opened 2022-11-22 10:25 UTC
Hi team.

We just noticed that newest push of v1 tag broke our github workflow.
We're getting errror:

```Run azure/docker-login@v1
  with:
    login-server: r1k8sacrdev.azurecr.io
    username: ***
    password: ***
  env:
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
    prisma-username: ***
    prisma-password: ***
    jira-password: ***
    jira-username: ***
    acr-client-id: ***
    acr-client-secret: ***
    github-token: ***
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@actions/core'
Require stack:
- /home/runner/work/_actions/azure/docker-login/v1/lib/login.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/runner/work/_actions/azure/docker-login/v1/lib/login.js:13:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:11[53](https://github.com/relativityone/veron-t/actions/runs/3522357286/jobs/5905245813#step:4:56):10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/work/_actions/azure/docker-login/v1/lib/login.js' ]
}```

We're using docker-login to log into Azure ACR, example usage:

``` - name: Login to Azure container registry
      uses: azure/docker-login@v1
      with:
        login-server: "some-acr.azurecr.io"
        username: "some-username"
        password: "some-password"```

Let me know if there is something else I should provide.

**Comment by ChillyBots** [comment] 2022-11-22 10:27
Same issue for us

**Comment by Yagya-omnius** [comment] 2022-11-22 10:28
Same issue we faced, breaking all our pipeline

**Comment by ChillyBots** [comment] 2022-11-22 10:31
Duplicate of https://github.com/Azure/docker-login/issues/48

There is a temp fix: https://github.com/Azure/docker-login/issues/48#issuecomment-1323443350

**Comment by BALAGA-GAYATRI** [comment] 2022-11-22 10:40
Please check now. I have fixed it.

**Comment by NathanHazout** [comment] 2022-11-22 10:49
works now, thanks

**Closed as completed by NathanHazout** 2022-11-22 10:49 UTC
Labels: need-to-triage
